### ISSUE TITLE
TCPDF ERROR: XObject "Template" doesn't exist

### ISSUE THREAD

**Issue by queirozfcom** [tecnickcom/TCPDF#3]
Hello there Nicola.

I've used your software for some months and I had no trouble at all.

However, I've tried installing a project on my friend's machine (PHP 5.5 on Windows) and I can't output PDF because I keep getting this error message:

> XObject "Template" doesn't exist

I have the exact same code on a Linux machine (but running on PHP 5.4) and this problem **does not** occur.

Do have any idea as to what could be happening?

**Oh yes I forgot to mention.** I'm using version 6.0.057 on Linux (PHP 5.4 - no errors here). I've tried the same version on Windows (PHP 5.5) and I've also trie dthe latest version (6.0.091) and I've had errors in both versions.

Thank you for having written such a useful piece of code and thank you for helping out!

**Comment by suabo** [comment]
I had the same error Message an it was after updating TCPDF. For me it was the Header() method, my custom one wasn't compatible with the new version.

I had to change this part at the end of my custom Header() method:
```

        if ($this->booklet AND (($this->page % 2) == 0)) {
            // adjust margins for booklet mode
            $dx = ($this->original_lMargin - $this->original_rMargin);
        }
```
to this:
```
        if (!$this->header_xobj_autoreset AND $this->booklet AND (($this->page % 2) == 0)) {
            // adjust margins for booklet mode
            $dx = ($this->original_lMargin - $this->original_rMargin);
        }
```
Hope this will help somebody updating TCPDF.

Since this is one of the first hits on google for me and there was nothing on stackoverflow i decided to give this hint here in this closed issue. Sorry for bothering @nicolaasuni =)
Thanks for putting the work into letting us install TCPDF via composer.
